name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-musl

          - os-name: Linux-aarch64
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-musl

          - os-name: Linux-riscv64
            runs-on: ubuntu-24.04
            target: riscv64gc-unknown-linux-gnu

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc

          - os-name: macOS-x86_64
            runs-on: macos-latest
            target: x86_64-apple-darwin

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.0

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release --manifest-path harbor/engine/Cargo.toml"
          strip: true
        env:
          CC_x86_64_unknown_linux_musl: zig cc -target x86_64-linux-musl
          CXX_x86_64_unknown_linux_musl: zig c++ -target x86_64-linux-musl

          CC_aarch64_unknown_linux_musl: zig cc -target aarch64-linux-musl
          CXX_aarch64_unknown_linux_musl: zig c++ -target aarch64-linux-musl

      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: harbor
          target: ${{ matrix.platform.target }}
